### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghm17** [mxjki/EfficientMaxEigenpair#5]
I have run into error, the message follows:
Error in if (sum(sign(wk)) == length(wk) | sum(sign(wk)) == -length(wk)) { :
  missing value where TRUE/FALSE needed.
I don't know what's wrong.

**Comment by mxjki** [comment]
Could you provide more details? For example, the problem you are solving, the initial values...

**Comment by mxjki** [comment]
> I have run into error, the message follows:
> Error in if (sum(sign(wk)) == length(wk) | sum(sign(wk)) == -length(wk)) { :
> missing value where TRUE/FALSE needed.
> I don't know what's wrong.

Could you provide more details? For example, the problem you are solving, the initial values...

**Comment by mxjki** [comment]
Could you provide more details? For example, the problem you are solving, the initial values...

**Comment by ghm17** [comment]
I want to compute the maximal eigenvalue of a 743dimensional symmetric matrix, the initial value is just rep(1, 743), I have tried another initial values, e.g. rnorm(743), but the error still shows up. 
I have used this function to compute lots of eigenvalues well, but this time it breaks for a small matrix so I am confused.

**Comment by mxjki** [comment]
Is that possible for you to show me your 743dimensional symmetric matrix? You can tell me how to construct it or send me raw data directly.

**Comment by ghm17** [comment]
It's a correlation matrix generated by the genetic data. 
[chr21_ld_diag3.txt](https://github.com/mxjki/EfficientMaxEigenpair/files/3056924/chr21_ld_diag3.txt)

**Comment by mxjki** [comment]
Sorry for the late! I want to confirm which function run into the error, is that "eff.ini.maxeig.general"?
